baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stevans Coding Blog'
theme = "paper"
[pagination]
pagerSize = 10  # Replace this with your desired pagination size

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'stevan06v'               # twitter.com/YOUR_TWITTER_ID
  github = 'stevan06v'                 # github.com/YOUR_GITHUB_ID
  instagram = 'stevan._v'           # instagram.com/YOUR_INSTAGRAM_ID            # threads.net/@YOUR_THREADS_ID
  DisqusShortname = "your-disqus-shortname"
  # home page profile
  avatar = 'https://1.gravatar.com/avatar/2d06f075a7aae436b97c6f9c3478dd36bcdad05a240442496ccdb42cf92ef25a?size=256 1x, https://1.gravatar.com/avatar/2d06f075a7aae436b97c6f9c3478dd36bcdad05a240442496ccdb42cf92ef25a?size=512 2x'                 # gravatar email or image url
  name = 'Stevan Vlajic'
  bio = 'Hey 👋, I am Stevan Vlajic a software engineer based in Austria. I kinda like coding so I came up with the idea to summarize some programming fundamentals and projects I have worked on in this blog :). Steve Jobs once said: "We’re here to put a dent in the universe. Otherwise why else even be here?". With that said - have fun using my personal coding blog as a learning resource and put a dent in the universe I guess ;)!'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
category = "categories"
tag = "tags"


[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 9

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[security.exec]
    allow = ['^asciidoctor$']
