baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Stevans Coding Blog'
theme = "paper"


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'stevan06v'               # twitter.com/YOUR_TWITTER_ID
  github = 'stevan06v'                 # github.com/YOUR_GITHUB_ID
  instagram = 'stevan._v'           # instagram.com/YOUR_INSTAGRAM_ID            # threads.net/@YOUR_THREADS_ID

  # home page profile
  avatar = 'https://de.gravatar.com/avatar/26cb2beceecb325a91e8afdd7d5e0ffc?size=256&cache=1714309459682'                 # gravatar email or image url
  name = 'Stevan Vlajic'
  bio = 'Hey 👋, I am Stevan Vlajic a software engineer based in Austria. Have fun using my personal coding blog as a learining resource.'

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 9

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10


[security.exec]
    allow = ['^asciidoctor$']